const fileInput=document.getElementById("file-input")
const clearBtn=document.getElementById("clear-data")
const searchText=document.getElementById("search-text")
const scoreMin=document.getElementById("score-min")
const scoreMax=document.getElementById("score-max")
const helpfulnessThreshold=document.getElementById("helpfulness-threshold")
const priceFilter=document.getElementById("price-filter")
const applyFiltersBtn=document.getElementById("apply-filters")
const resetFiltersBtn=document.getElementById("reset-filters")
const exportCsvBtn=document.getElementById("export-csv")
const totalReviewsEl=document.getElementById("total-reviews")
const uniqueProductsEl=document.getElementById("unique-products")
const averageScoreEl=document.getElementById("average-score")
const missingPricesEl=document.getElementById("missing-prices")
const tableBody=document.querySelector("#reviews-table tbody")
const tableHead=document.querySelector("#reviews-table thead")
const pageInfo=document.getElementById("page-info")
const prevPageBtn=document.getElementById("prev-page")
const nextPageBtn=document.getElementById("next-page")
const pageSizeSelect=document.getElementById("page-size")
const scoreCanvas=document.getElementById("score-chart")
const dbStatus=document.getElementById("db-status")
const showDataCard=document.getElementById("show-datacard")
const modal=document.getElementById("datacard-modal")
const modalClose=document.getElementById("modal-close")
const dataCardBody=document.getElementById("datacard-body")
const runPredictBtn=document.getElementById("run-predict")
const predLimit=document.getElementById("pred-limit")
const predOffset=document.getElementById("pred-offset")
const clusterCanvas=document.getElementById("cluster-chart")
let originalData=[]
let filteredData=[]
let page=1
let pageSize=10
let sortKey=null
let sortAsc=true
let apiMode=false
let apiMeta={}
let columnVisibility={}
const API_BASE=location.protocol==="file:"?"http://localhost:8000":""
const apiUrl=(path)=>API_BASE?`${API_BASE}${path}`:path
function parseCSV(text){const rows=[];let i=0;let current="";let inQuotes=false;let row=[];function pushCell(){row.push(current);current=""}while(i<text.length){const c=text[i];if(c==='\"'){if(inQuotes&&text[i+1]==='\"'){current+='\"';i++}else inQuotes=!inQuotes}else if(c===','&&!inQuotes){pushCell()}else if((c==='\n'||c==='\r')&&!inQuotes){if(current!==""||row.length>0){pushCell();rows.push(row);row=[]}current="";if(c==='\r'&&text[i+1]==='\n')i++}else{current+=c}i++}if(current!==""||row.length>0){pushCell();rows.push(row)}return rows}
function toNumber(x){const n=Number(x);return isNaN(n)?null:n}
function parseHelpfulness(x){if(!x)return null;const m=/^\s*(\d+)\s*\/\s*(\d+)\s*$/.exec(String(x));if(!m)return null;const a=Number(m[1]);const b=Number(m[2]);if(b===0)return null;return a/b}
function normalizeKeys(keys){return keys.map(k=>k.trim())}
function rowsToObjects(rows){if(rows.length===0)return[];const header=normalizeKeys(rows[0]);const objs=[];for(let r=1;r<rows.length;r++){const row=rows[r];const obj={};for(let c=0;c<header.length;c++){obj[header[c]]=row[c]??""}objs.push(obj)}return objs}
function mapRecord(rec){const id=rec["Id"]??rec["id"]??rec["product_id"]??rec["ProductId"]??"";const title=rec["Title"]??rec["title"]??"";const priceRaw=rec["Price"]??rec["price"]??"";const userId=rec["User_id"]??rec["user_id"]??rec["UserId"]??"";const profileName=rec["profileName"]??rec["ProfileName"]??rec["user_name"]??"";const helpfulRaw=rec["review/helpfulness"]??rec["helpfulness"]??"";const scoreRaw=rec["review/score"]??rec["score"]??"";const timeRaw=rec["review/time"]??rec["time"]??"";const summary=rec["review/summary"]??rec["summary"]??"";const text=rec["review/text"]??rec["text"]??"";return{Id:String(id),Title:String(title),Price:priceRaw===null||priceRaw===undefined||priceRaw===""?null:toNumber(priceRaw),User_id:String(userId),profileName:String(profileName),helpfulness:parseHelpfulness(helpfulRaw),helpfulnessRaw:String(helpfulRaw||""),score:toNumber(scoreRaw),time:toNumber(timeRaw),summary:String(summary),text:String(text)}}
function computeSummary(data){const total=data.length;const products=new Set(data.map(d=>d.Id));const avg=total===0?0:(data.reduce((a,b)=>a+(b.score||0),0)/total);const missing=data.reduce((a,b)=>a+(b.Price===null?1:0),0);return{total,uniqueProducts:products.size,averageScore:avg,missingPrices:missing}}
function renderSummaryLocal(){const s=computeSummary(filteredData);totalReviewsEl.textContent=String(s.total);uniqueProductsEl.textContent=String(s.uniqueProducts);averageScoreEl.textContent=s.averageScore.toFixed(2);missingPricesEl.textContent=String(s.missingPrices)}
function setColumnVisibility(key,visible){columnVisibility[key]=visible;const th=tableHead.querySelector(`th[data-key="${key}"]`);if(!th)return;const idx=[...th.parentElement.children].indexOf(th);th.style.display=visible?"":"none";for(const tr of tableBody.querySelectorAll("tr")){const td=tr.children[idx];if(td)td.style.display=visible?"":"none"}}
function applyColumnVisibility(){for(const [key,visible] of Object.entries(columnVisibility)){setColumnVisibility(key,visible)}}
function updateAvailability(meta){apiMeta=meta||{};const hasScore=apiMeta.has_score!==false;const hasPrice=apiMeta.has_price!==false;const hasHelp=apiMeta.has_helpfulness!==false;const hasSummary=apiMeta.has_summary!==false;scoreMin.disabled=!hasScore;scoreMax.disabled=!hasScore;priceFilter.disabled=!hasPrice;helpfulnessThreshold.disabled=!hasHelp;if(!hasScore){scoreMin.value="any";scoreMax.value="any";averageScoreEl.textContent="N/A"}if(!hasPrice){priceFilter.value="any";missingPricesEl.textContent="N/A"}if(!hasHelp){helpfulnessThreshold.value="0"}setColumnVisibility("review/score",hasScore);setColumnVisibility("Price",hasPrice);setColumnVisibility("review/helpfulness",hasHelp);setColumnVisibility("review/summary",hasSummary);setColumnVisibility("review/text",true)}
function applyFiltersLocal(){const q=searchText.value.trim().toLowerCase();const sMin=scoreMin.value;const sMax=scoreMax.value;const h=Number(helpfulnessThreshold.value);const p=priceFilter.value;filteredData=originalData.filter(d=>{if(sMin!=="any"||sMax!=="any"){if(d.score===null)return false;const s=Number(d.score);if(sMin!=="any"&&s<Number(sMin))return false;if(sMax!=="any"&&s>Number(sMax))return false}if(p==="has"&&d.Price===null)return false;if(p==="missing"&&d.Price!==null)return false;if(h>0&&(d.helpfulness===null||d.helpfulness<h))return false;if(q){const t=(d.Title+" "+d.summary+" "+d.text).toLowerCase();if(!t.includes(q))return false}return true});page=1;sortAndRenderLocal()}
function sortAndRenderLocal(){if(sortKey){filteredData.sort((a,b)=>{const va=a[sortKey]??a[sortKey.replace("/","")];const vb=b[sortKey]??b[sortKey.replace("/","")];if(va==null&&vb==null)return 0;if(va==null)return 1;if(vb==null)return -1;if(va<vb)return sortAsc?-1:1;if(va>vb)return sortAsc?1:-1;return 0})}renderSummaryLocal();renderChartLocal();renderTableLocal()}
function renderChartLocal(){const ctx=scoreCanvas.getContext("2d");ctx.clearRect(0,0,scoreCanvas.width,scoreCanvas.height);const bins=[1,2,3,4,5];const counts=bins.map(b=>filteredData.reduce((a,d)=>a+(d.score===b?1:0),0));const max=Math.max(0,...counts);const w=scoreCanvas.width;const h=scoreCanvas.height;const pad=24;if(max===0){ctx.fillStyle="#cbd5e1";ctx.textAlign="center";ctx.font="14px system-ui";ctx.fillText("No scored reviews for current filters",w/2,h/2);return}const bw=(w-2*pad)/bins.length*0.7;const gap=((w-2*pad)-bins.length*bw)/bins.length;ctx.fillStyle="#94a3b8";ctx.strokeStyle="#374151";ctx.lineWidth=1;for(let i=0;i<bins.length;i++){const x=pad+i*(bw+gap)+gap/2;const bh=(h-2*pad)*(counts[i]/Math.max(1,max));const y=h-pad-bh;ctx.fillRect(x,y,bw,bh);ctx.strokeRect(x,y,bw,bh);ctx.fillStyle="#cbd5e1";ctx.textAlign="center";ctx.font="12px system-ui";ctx.fillText(String(bins[i]),x+bw/2,h-pad+14);ctx.fillStyle="#94a3b8"}ctx.fillStyle="#cbd5e1";ctx.textAlign="left";ctx.font="12px system-ui";ctx.fillText("Count",8,12)}
function renderTableLocal(){pageSize=Number(pageSizeSelect.value);const start=(page-1)*pageSize;const rows=filteredData.slice(start,start+pageSize);tableBody.innerHTML="";for(const d of rows){const tr=document.createElement("tr");const price=d.Price==null?"":String(d.Price);const helpful=d.helpfulnessRaw||"";tr.innerHTML=`<td>${escapeHtml(d.Id)}</td><td>${escapeHtml(d.Title)}</td><td>${escapeHtml(price)}</td><td>${escapeHtml(String(d.score))}</td><td>${escapeHtml(helpful)}</td><td>${escapeHtml(d.profileName)}</td><td>${escapeHtml(d.summary)}</td><td>${escapeHtml(d.text)}</td>`;tableBody.appendChild(tr)}const pages=Math.max(1,Math.ceil(filteredData.length/pageSize));if(page>pages)page=pages;pageInfo.textContent=`Page ${page} / ${pages}`;prevPageBtn.disabled=page<=1;nextPageBtn.disabled=page>=pages}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function exportCSVLocal(){const header=["Id","Title","Price","User_id","profileName","review/helpfulness","review/score","review/time","review/summary","review/text"];const lines=[header.join(",")];for(const d of filteredData){const row=[d.Id,d.Title,d.Price??"",d.User_id,d.profileName,d.helpfulnessRaw??"",d.score??"",d.time??"",d.summary,d.text].map(v=>csvField(String(v)));lines.push(row.join(","))}const blob=new Blob([lines.join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="filtered_reviews.csv";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csvField(s){const needs=/[",\n\r]/.test(s);if(!needs)return s;return "\""+s.replace(/\"/g,"\"\"")+"\""}
function loadJSON(text){const arr=JSON.parse(text);const mapped=Array.isArray(arr)?arr.map(mapRecord):[];originalData=mapped;filteredData=mapped.slice();page=1;sortKey=null;sortAsc=true;sortAndRenderLocal()}
function loadCSV(text){const rows=parseCSV(text);const objs=rowsToObjects(rows).map(mapRecord);originalData=objs;filteredData=objs.slice();page=1;sortKey=null;sortAsc=true;sortAndRenderLocal()}
function handleFile(){const f=fileInput.files[0];if(!f)return;const isJson=f.name.toLowerCase().endsWith(".json");const reader=new FileReader();reader.onload=()=>{try{isJson?loadJSON(reader.result):loadCSV(reader.result)}catch(err){alert("Failed to load file")}};reader.readAsText(f)}
function clearData(){originalData=[];filteredData=[];page=1;sortKey=null;sortAsc=true;tableBody.innerHTML="";renderSummaryLocal();renderChartLocal();pageInfo.textContent="Page 1"}
fileInput.addEventListener("change",handleFile)
clearBtn.addEventListener("click",clearData)
applyFiltersBtn.addEventListener("click",applyFiltersLocal)
resetFiltersBtn.addEventListener("click",()=>{searchText.value="";scoreMin.value="1";scoreMax.value="5";helpfulnessThreshold.value="0";priceFilter.value="any";applyFiltersLocal()})
tableHead.addEventListener("click",e=>{const th=e.target.closest("th");if(!th)return;const key=th.getAttribute("data-key");if(!key)return;if(sortKey===key)sortAsc=!sortAsc;else{sortKey=key;sortAsc=true}sortAndRenderLocal()})
prevPageBtn.addEventListener("click",()=>{if(page>1){page--;renderTableLocal();pageInfo.textContent=`Page ${page} / ${Math.max(1,Math.ceil(filteredData.length/pageSize))}`}})
nextPageBtn.addEventListener("click",()=>{const pages=Math.max(1,Math.ceil(filteredData.length/pageSize));if(page<pages){page++;renderTableLocal();pageInfo.textContent=`Page ${page} / ${pages}`}})
pageSizeSelect.addEventListener("change",()=>{page=1;renderTableLocal();pageInfo.textContent=`Page ${page} / ${Math.max(1,Math.ceil(filteredData.length/pageSize))}`})
exportCsvBtn.addEventListener("click",exportCSVLocal)
renderSummaryLocal()
renderChartLocal()
async function tryApi(){try{const r=await fetch(apiUrl("/api/stats"));if(r.ok){dbStatus.textContent="DB: connected";return true}}catch(e){}dbStatus.textContent="DB: offline";return false}
function qs(){const p=new URLSearchParams();const q=searchText.value.trim();if(q)p.set("q",q);if(scoreMin.value!=="any")p.set("score_min",scoreMin.value);if(scoreMax.value!=="any")p.set("score_max",scoreMax.value);const h=helpfulnessThreshold.value;if(h)p.set("helpfulness",h);const pf=priceFilter.value;if(pf!=="any")p.set("price",pf);if(sortKey)p.set("sort_key",sortKey==="review/score"?"review_score":sortKey);p.set("sort_order",sortAsc?"asc":"desc");return p}
async function applyFiltersApi(){const p=qs();const ps=Number(pageSizeSelect.value);p.set("page",String(page));p.set("page_size",String(ps));try{const sRes=await fetch(apiUrl("/api/stats?"+p.toString()));if(!sRes.ok)throw new Error("stats");const s=await sRes.json();totalReviewsEl.textContent=String(s.total);uniqueProductsEl.textContent=String(s.unique_products);averageScoreEl.textContent=Number(s.average_score).toFixed(2);missingPricesEl.textContent=String(s.missing_prices);updateAvailability(s);const rRes=await fetch(apiUrl("/api/reviews?"+p.toString()));if(!rRes.ok)throw new Error("reviews");const r=await rRes.json();filteredData=r.rows||[];renderChartApi(s.histogram||{});renderTableApi(r.total||0,ps)}catch(e){dbStatus.textContent="DB: offline";setTimeout(applyFiltersApi,2000)}}
function renderChartApi(hist){const ctx=scoreCanvas.getContext("2d");ctx.clearRect(0,0,scoreCanvas.width,scoreCanvas.height);const w=scoreCanvas.width;const h=scoreCanvas.height;if(apiMeta.has_score===false){ctx.fillStyle="#cbd5e1";ctx.textAlign="center";ctx.font="14px system-ui";ctx.fillText("Score column not available in database",w/2,h/2);return}const bins=[1,2,3,4,5];const counts=bins.map(b=>Number(hist[String(b)]||0));const max=Math.max(0,...counts);const pad=24;if(max===0){ctx.fillStyle="#cbd5e1";ctx.textAlign="center";ctx.font="14px system-ui";ctx.fillText("No scored reviews in database or current filters",w/2,h/2);return}const bw=(w-2*pad)/bins.length*0.7;const gap=((w-2*pad)-bins.length*bw)/bins.length;ctx.fillStyle="#94a3b8";ctx.strokeStyle="#374151";ctx.lineWidth=1;for(let i=0;i<bins.length;i++){const x=pad+i*(bw+gap)+gap/2;const bh=(h-2*pad)*(counts[i]/Math.max(1,max));const y=h-pad-bh;ctx.fillRect(x,y,bw,bh);ctx.strokeRect(x,y,bw,bh);ctx.fillStyle="#cbd5e1";ctx.textAlign="center";ctx.font="12px system-ui";ctx.fillText(String(bins[i]),x+bw/2,h-pad+14);ctx.fillStyle="#94a3b8"}ctx.fillStyle="#cbd5e1";ctx.textAlign="left";ctx.font="12px system-ui";ctx.fillText("Count",8,12)}
function renderClusterChart(dist){const ctx=clusterCanvas.getContext("2d");ctx.clearRect(0,0,clusterCanvas.width,clusterCanvas.height);const labels=Object.keys(dist).sort((a,b)=>Number(a)-Number(b));const counts=labels.map(l=>dist[l]);const max=Math.max(0,...counts);const w=clusterCanvas.width;const h=clusterCanvas.height;const pad=24;if(max===0){ctx.fillStyle="#cbd5e1";ctx.textAlign="center";ctx.font="14px system-ui";ctx.fillText("No predictions yet",w/2,h/2);return}const bw=(w-2*pad)/labels.length*0.7;const gap=((w-2*pad)-labels.length*bw)/labels.length;ctx.fillStyle="#94a3b8";ctx.strokeStyle="#374151";ctx.lineWidth=1;for(let i=0;i<labels.length;i++){const x=pad+i*(bw+gap)+gap/2;const bh=(h-2*pad)*(counts[i]/Math.max(1,max));const y=h-pad-bh;ctx.fillRect(x,y,bw,bh);ctx.strokeRect(x,y,bw,bh);ctx.fillStyle="#cbd5e1";ctx.textAlign="center";ctx.font="12px system-ui";ctx.fillText(String(labels[i]),x+bw/2,h-pad+14);ctx.fillStyle="#94a3b8"}ctx.fillStyle="#cbd5e1";ctx.textAlign="left";ctx.font="12px system-ui";ctx.fillText("Count",8,12)}
async function runPredict(){try{const limit=Math.max(1,Number(predLimit.value)||1000);const offset=Math.max(0,Number(predOffset.value)||0);const r=await fetch(apiUrl(`/api/predict?limit=${limit}&offset=${offset}`));if(!r.ok){let msg="Prediction failed";try{const j=await r.json();if(j&&j.error)msg=`Prediction failed: ${j.error}`}catch(e){}alert(msg);return}const j=await r.json();const ids=j.ids||[];const labels=j.labels||[];const dist={};for(const l of labels){const k=String(l);dist[k]=(dist[k]||0)+1}renderClusterChart(dist);for(let i=0;i<Math.min(filteredData.length,labels.length);i++){filteredData[i].cluster=labels[i]}}catch(e){alert("Prediction error")}}
function renderTableApi(total,ps){tableBody.innerHTML="";for(const d of filteredData){const tr=document.createElement("tr");const price=d.Price==null?"":String(d.Price);const helpful=d["review/helpfulness"]||"";const score=d["review/score"];tr.innerHTML=`<td>${escapeHtml(d.Id)}</td><td>${escapeHtml(d.Title)}</td><td>${escapeHtml(price)}</td><td>${escapeHtml(String(score))}</td><td>${escapeHtml(helpful)}</td><td>${escapeHtml(d.profileName||"")}</td><td>${escapeHtml(d["review/summary"]||"")}</td><td>${escapeHtml(d["review/text"]||"")}</td>`;tableBody.appendChild(tr)}applyColumnVisibility();const pages=Math.max(1,Math.ceil(total/ps));if(page>pages)page=pages;pageInfo.textContent=`Page ${page} / ${pages}`;prevPageBtn.disabled=page<=1;nextPageBtn.disabled=page>=pages}
function exportCSVApi(){const a=document.createElement("a");a.href=apiUrl("/api/export?"+qs().toString());a.download="filtered_reviews.csv";document.body.appendChild(a);a.click();a.remove()}
function enableApiMode(){if(apiMode)return;apiMode=true;applyFiltersBtn.removeEventListener("click",applyFiltersLocal);applyFiltersBtn.addEventListener("click",()=>{page=1;applyFiltersApi()});resetFiltersBtn.removeEventListener("click",()=>{});resetFiltersBtn.addEventListener("click",()=>{searchText.value="";scoreMin.value="1";scoreMax.value="5";helpfulnessThreshold.value="0";priceFilter.value="any";page=1;applyFiltersApi()});tableHead.addEventListener("click",e=>{const th=e.target.closest("th");if(!th)return;const key=th.getAttribute("data-key");if(!key)return;if(sortKey===key)sortAsc=!sortAsc;else{sortKey=key;sortAsc=true}applyFiltersApi()});prevPageBtn.addEventListener("click",()=>{if(page>1){page--;applyFiltersApi()}});nextPageBtn.addEventListener("click",()=>{page++;applyFiltersApi()});pageSizeSelect.addEventListener("change",()=>{page=1;applyFiltersApi()});exportCsvBtn.removeEventListener("click",exportCSVLocal);exportCsvBtn.addEventListener("click",exportCSVApi);applyFiltersApi()}
enableApiMode()
function openModal(){modal.classList.remove("hidden")}
function closeModal(){modal.classList.add("hidden")}
async function loadDataCard(){dataCardBody.innerHTML="";try{const r=await fetch(apiUrl("/api/datacard"));if(r.ok){const j=await r.json();const items=j.items||[];if(items.length){const ul=document.createElement("ul");for(const it of items){const li=document.createElement("li");li.textContent=it.name+" — "+it.description;ul.appendChild(li)}dataCardBody.appendChild(ul);return}}}catch(e){}const fields=["Id","Title","Price","User_id","profileName","review/helpfulness","review/score","review/time","review/summary","review/text"];const ul=document.createElement("ul");for(const f of fields){const li=document.createElement("li");li.textContent=f;ul.appendChild(li)}dataCardBody.appendChild(ul)}
showDataCard.addEventListener("click",()=>{openModal();loadDataCard()})
modalClose.addEventListener("click",closeModal)
modal.addEventListener("click",e=>{if(e.target===modal)closeModal()})
runPredictBtn.addEventListener("click",runPredict)
